name: Build Docker development container

on:
  push:
    branches:
      - master
      - 'build-docker'
    tags:
      - '*'
      - '!v*'
  workflow_dispatch:

jobs:
  docker_images:
    strategy:
      matrix:
        os: [22.04, 24.04]
        vm: [ubuntu-latest, ubuntu-24.04-arm]
        include:
          - vm: ubuntu-latest
            arch: amd
            platform: linux/amd64
          - vm: ubuntu-24.04-arm
            arch: arm
            platform: linux/arm64,linux/arm/v7
    runs-on: ${{ matrix.vm }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: ghcr.io/signalk/signalk-server:${{ matrix.arch }}-${{ matrix.os }}-${{ github.run_id }}
          build-args: |
            REGISTRY=ghcr.io
            UBUNTU_VERSION=${{ matrix.os }}
  create-and-push-manifest:
    needs: docker_images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [22.04, 24.04]
        include:
          - os: 24.04
            suffix: -24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: |
            signalk/signalk-server
            ghcr.io/signalk/signalk-server
          tags: |
            type=ref,event=branch
            type=sha
          flavor: |
            suffix=${{ matrix.suffix }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: signalkci
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Create and push multi-arch manifest to GHCR and Docker Hub
        uses: int128/docker-manifest-create-action@v2
        with:
          tags: |
            ${{ steps.docker_meta.outputs.tags }}
          sources: |
            ghcr.io/signalk/signalk-server:amd-${{ matrix.os }}-${{ github.run_id }}
            ghcr.io/signalk/signalk-server:arm-${{ matrix.os }}-${{ github.run_id }}

  housekeeping:
    needs: create-and-push-manifest
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Remove Temporary & Untagged Docker Images from GHCR
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          packages: signalk-server
          delete-untagged: true
          delete-tags: amd-22.04-${{ github.run_id }},arm-22.04-${{ github.run_id }},amd-24.04-${{ github.run_id }},arm-24.04-${{ github.run_id }}
          token: ${{ secrets.GHCR_PAT }}
